"""Initial migrate

Revision ID: acff3046c539
Revises: 
Create Date: 2025-07-17 16:00:02.182944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = 'acff3046c539'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_of_collect',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('article', sa.String(), nullable=False),
        sa.Column('pad_len', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('article'),
        schema='figure'
    )

    # Определяем "виртуальную" таблицу для bulk_insert
    type_tbl = table(
        'type_of_collect',
        column('article', sa.String),
        column('name', sa.String),
        column('pad_len', sa.Integer),
        schema='figure'
    )

    op.bulk_insert(
        type_tbl,
        [
            {'article':'ac',        'name':'Space',                           'pad_len':3},
            {'article':'agt',       'name':'Agents',                          'pad_len':3},
            {'article':'air',       'name':'Town',                            'pad_len':3},
            {'article':'ani',       'name':'Animal Crossing',                 'pad_len':3},
            {'article':'aqu',       'name':'Aquazone',                        'pad_len':3},
            {'article':'bnk',       'name':'Town',                            'pad_len':3},
            {'article':'boat',      'name':'Town',                            'pad_len':3},
            {'article':'bob',       'name':'SpongeBob SquarePants',           'pad_len':3},
            {'article':'car',       'name':'Town',                            'pad_len':3},
            {'article':'cas',       'name':'Castle',                          'pad_len':3},
            {'article':'col',       'name':'Collectible Minifigures',         'pad_len':3},
            {'article':'colhp',     'name':'Collectible Minifigures',         'pad_len':2},
            {'article':'collt',     'name':'Collectible Minifigures',         'pad_len':2},
            {'article':'colmar',    'name':'Collectible Minifigures',         'pad_len':2},
            {'article':'colsh',     'name':'Collectible Minifigures',         'pad_len':2},
            {'article':'coltlnm',   'name':'Collectible Minifigures',         'pad_len':2},
            {'article':'coltm',     'name':'Collectible Minifigures',         'pad_len':2},
            {'article':'con',       'name':'Town',                            'pad_len':3},
            {'article':'cop',       'name':'Town',                            'pad_len':3},
            {'article':'cre',       'name':'4 Juniors',                       'pad_len':3},
            {'article':'crs',       'name':'Cars',                            'pad_len':3},
            {'article':'cty',       'name':'Town',                            'pad_len':4},
            {'article':'dfb',       'name':'Collectible Minifigures',         'pad_len':3},
            {'article':'dim',       'name':'Dimensions',                      'pad_len':3},
            {'article':'din',       'name':'Dino Attack',                     'pad_len':3},
            {'article':'dino',      'name':'Dino',                            'pad_len':3},
            {'article':'dis',       'name':'Collectible Minifigures',         'pad_len':3},
            {'article':'div',       'name':'Town',                            'pad_len':3},
            {'article':'dp',        'name':'Disney',                          'pad_len':3},
            {'article':'dun',       'name':'Dune',                            'pad_len':3},
            {'article':'dupclock',  'name':'DUPLO',                           'pad_len':2},
            {'article':'dupmermaid','name':'DUPLO',                           'pad_len':2},
            {'article':'edu',       'name':'Educational & Dacta',             'pad_len':3},
            {'article':'env',       'name':'Town',                            'pad_len':3},
            {'article':'fire',      'name':'Town',                            'pad_len':3},
            {'article':'gb',        'name':'LEGO Ideas (CUUSOO)',             'pad_len':3},
            {'article':'gdh',       'name':'Gabby\'s Dollhouse',             'pad_len':3},
            {'article':'gen',       'name':'Collectible Minifigures',         'pad_len':3},
            {'article':'gs',        'name':'Space',                           'pad_len':3},
            {'article':'hol',       'name':'Holiday & Event',                 'pad_len':3},
            {'article':'hp',        'name':'Harry Potter',                    'pad_len':3},
            {'article':'iaj',       'name':'Indiana Jones',                   'pad_len':3},
            {'article':'idea',      'name':'LEGO Ideas (CUUSOO)',             'pad_len':3},
            {'article':'jail',      'name':'Town',                            'pad_len':3},
            {'article':'jbl',       'name':'Town',                            'pad_len':3},
            {'article':'js',        'name':'4 Juniors',                       'pad_len':3},
            {'article':'jw',        'name':'Jurassic World',                  'pad_len':3},
            {'article':'lom',       'name':'Space',                           'pad_len':3},
            {'article':'mar',       'name':'Super Mario',                     'pad_len':4},
            {'article':'mck',       'name':'Disney',                          'pad_len':3},
            {'article':'min',       'name':'Minecraft',                       'pad_len':3},
            {'article':'mk',        'name':'Monkie Kid',                      'pad_len':3},
            {'article':'mm',        'name':'Space',                           'pad_len':3},
            {'article':'mnn',       'name':'Despicable Me and Minions',       'pad_len':3},
            {'article':'mof',       'name':'Holiday & Event',                 'pad_len':3},
            {'article':'nex',       'name':'NEXO KNIGHTS',                    'pad_len':3},
            {'article':'njo',       'name':'NINJAGO',                         'pad_len':4},
            {'article':'oct',       'name':'Town',                            'pad_len':3},
            {'article':'ovr',       'name':'Town',                            'pad_len':3},
            {'article':'par',       'name':'Town',                            'pad_len':3},
            {'article':'post',      'name':'Town',                            'pad_len':3},
            {'article':'ppg',       'name':'The Powerpuff Girls',             'pad_len':3},
            {'article':'rac',       'name':'Racers',                          'pad_len':3},
            {'article':'rck',       'name':'Rock Raiders',                    'pad_len':3},
            {'article':'rep',       'name':'Town',                            'pad_len':3},
            {'article':'res',       'name':'Town',                            'pad_len':3},
            {'article':'scaFemA',   'name':'Scala',                           'pad_len':2},
            {'article':'scaFemY',   'name':'Scala',                           'pad_len':2},
            {'article':'scd',       'name':'Scooby-Doo',                      'pad_len':3},
            {'article':'sh',        'name':'Super Heroes',                    'pad_len':4},
            {'article':'sim',       'name':'Collectible Minifigures',         'pad_len':3},
            {'article':'sp',        'name':'Space',                           'pad_len':3},
            {'article':'splc',      'name':'Town',                            'pad_len':3},
            {'article':'sr',        'name':'Speed Racer',                     'pad_len':3},
            {'article':'sw',        'name':'Star Wars',                       'pad_len':4},
            {'article':'tgb',       'name':'Collectible Minifigures',         'pad_len':3},
            {'article':'tlm',       'name':'The LEGO Movie',                  'pad_len':3},
            {'article':'toy',       'name':'Toy Story',                       'pad_len':3},
            {'article':'trn',       'name':'Town',                            'pad_len':3},
            {'article':'twn',       'name':'Town',                            'pad_len':3},
            {'article':'vid',       'name':'Vidiyo',                          'pad_len':3},
            {'article':'wc',        'name':'Town',                            'pad_len':3},
            {'article':'wr',        'name':'World Racers',                    'pad_len':3},
            {'article':'wtr',       'name':'Town',                            'pad_len':3},
            {'article':'x',         'name':'Scala',                           'pad_len':2},
        ]
    )

    # остальная часть миграции
    op.create_table('figures',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('bricklink_id', sa.String(), nullable=False),
        sa.Column('type_collected_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['type_collected_id'], ['figure.type_of_collect.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bricklink_id'),
        schema='figure'
    )
    op.create_index(op.f('ix_figure_figures_id'), 'figures', ['id'], unique=False, schema='figure')
    op.create_table('figure_to_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('price_buy', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('price_sale', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('buy_date', sa.Date(), nullable=True),
        sa.Column('sale_date', sa.Date(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('figure_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['figure_id'], ['figure.figures.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='figure'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('figure_to_user', schema='figure')
    op.drop_index(op.f('ix_figure_figures_id'), table_name='figures', schema='figure')
    op.drop_table('figures', schema='figure')
    op.drop_table('type_of_collect', schema='figure')
    # ### end Alembic commands ###
