"""Initial Reminder

Revision ID: 57d5ffd62a20
Revises: edaef483f330
Create Date: 2025-07-13 21:00:24.314352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d5ffd62a20'
down_revision: Union[str, None] = 'edaef483f330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_price_buy', sa.Boolean(), nullable=True),
    sa.Column('request_price_sale', sa.Boolean(), nullable=True),
    sa.Column('is_seller', sa.Boolean(), nullable=True),
    sa.Column('show_description', sa.Boolean(), nullable=True),
    sa.Column('auto_fill_dates', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='auth'
    )
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='auth')
    op.drop_constraint(op.f('users_username_key'), 'users', schema='auth', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], schema='auth', postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='auth')
    op.drop_table('user_settings', schema='auth')
    # ### end Alembic commands ###
