"""Initial table

Revision ID: edaef483f330
Revises: 
Create Date: 2025-07-10 17:13:41.437638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edaef483f330'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_permission_group_id'), 'permission_group', ['id'], unique=False, schema='auth')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('telegram_username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_username'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_id'), 'users', ['id'], unique=False, schema='auth')
    op.create_table('permissions_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth.permission_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_permissions_name_id'), 'permissions_name', ['id'], unique=False, schema='auth')
    op.create_table('user_permission_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth.permission_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    schema='auth'
    )
    op.create_table('permission_group_permissions',
    sa.Column('permission_group_id', sa.Integer(), nullable=False),
    sa.Column('permission_name_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_group_id'], ['auth.permission_group.id'], ),
    sa.ForeignKeyConstraint(['permission_name_id'], ['auth.permissions_name.id'], ),
    sa.PrimaryKeyConstraint('permission_group_id', 'permission_name_id'),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission_group_permissions', schema='auth')
    op.drop_table('user_permission_group', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_name_id'), table_name='permissions_name', schema='auth')
    op.drop_table('permissions_name', schema='auth')
    op.drop_index(op.f('ix_auth_users_id'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_permission_group_id'), table_name='permission_group', schema='auth')
    op.drop_table('permission_group', schema='auth')
    # ### end Alembic commands ###
